services:
  idempiere:
    image: idempiereofficial/idempiere:11-release
    ports:
      - 8080:8080
      - 8443:8443
      - 12612:12612
    volumes:
      - idempiere_config:/opt/idempiere/configuration
      - idempiere_plugins:/opt/idempiere/plugins

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - idempiere_data:/var/lib/postgresql/data

volumes:
  idempiere_data:
  idempiere_plugins:
  idempiere_config: